apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xd58sytu4-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/xd58sytu4-java-quarkus-gitops